version: '3'
services:

  database:
    image: mongo:latest
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      MONGODB_DATABASE: pixus
    volumes:
      - ./data/db:/data/db
    command: mongod --logpath=/dev/null --quiet

  pixus-server:
    build: .
    command: npm start
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - 1261:1261
    links:
      - database
    depends_on:
      - database
    environment:
      PORT: 1261
      NODE_ENV: development
      MONGODB_URI: mongodb://database:27017/pixus

  pixus-server-reverse-proxy:
    image: nginx:latest
    depends_on:
      - pixus-server
    volumes:
      - ./config/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./config/pixus.crt:/etc/nginx/pixus.crt
      - ./config/pixus.key:/etc/nginx/pixus.key
      - ./config/ssl_passwords:/etc/nginx/ssl_passwords
    ports:
      - 1260:1260
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
